#!/bin/bash

read -p "Введите путь к дирректории: " DELDIR

if [ -e $DELDIR ]
        then
                echo 'Директива не найдена'
                cd $DELDIR
                echo 'Удаление запущено'
                rm -v *.bak *.tmp *.backup
                echo 'Удаление завершено без ошибок'
        else
                echo 'Указанная дирректория не найдена! Выполнение остановлено'
                exit 2
fi
